// apps/demo-vue/src/App.vue
<template>
  <!-- TODO: 引入 ParticlePrinter 组件 -->
  <div style="width: 100vw; height: 100vh; background: #000;">
    <h1 style="color: #fff; text-align: center; padding-top: 2rem;">
      Particle Printer — Vue Demo
    </h1>
  </div>
</template>

<script setup lang="ts">
/**
 * Vue Demo — 使用 TresJS 测试 @particle-printer/vue
 */
</script>

// apps/demo-react/src/App.tsx
/**
 * React Demo — 使用 R3F 测试 @particle-printer/react
 */
export default function App() {
  return (
    <div style={{ width: '100vw', height: '100vh', background: '#000' }}>
      {/* TODO: 引入 ParticlePrinter 组件 */}
      <h1 style={{ color: '#fff', textAlign: 'center', paddingTop: '2rem' }}>
        Particle Printer — React Demo
      </h1>
    </div>
  )
}
